<?php

declare(strict_types=1);

/** @var Template block */

use Magento\Framework\View\Element\Template;

?>

<div>
    <ul class="social-icons">
        <li class="icons-item"><a href="#" rel="nofollow" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
        <li class="icons-item"><a href="#" rel="nofollow" target="_blank"><i class="fab fa-vimeo-v"></i></a></li>
        <li class="icons-item"><a href="#" rel="nofollow" target="_blank"><i class="fab fa-google-plus-g"></i></a></li>
        <li class="icons-item"><a href="#" rel="nofollow" target="_blank"><i class="fab fa-twitter"></i></a></li>
        <li class="icons-item"><a href="#" rel="nofollow" target="_blank"><i class="fab fa-pinterest-p"></i></a></li>
        <li class="icons-item"><a href="#" rel="nofollow" target="_blank"><i class="fab fa-youtube"></i></a></li>
    </ul>
</div>
