<?php
/** @var Magento\Framework\View\Element\Template **/
?>

<div>
    <ul class="social-icons">
        <li class="icons-facebook"><a href="#" rel="nofollow" target="_blank"></a></li>
        <li class="icons-vimeo"><a href="#" rel="nofollow" target="_blank"></a></li>
        <li class="icons-gplus"><a href="#" rel="nofollow" target="_blank"></a></li>
        <li class="icons-twitter"><a href="#" rel="nofollow" target="_blank"></a></li>
        <li class="icons-pinterest"><a href="#" rel="nofollow" target="_blank"></a></li>
        <li class="icons-youtube"><a href="#" rel="nofollow" target="_blank"></a></li>
    </ul>
</div>
