<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>

<div class="featured-content">
    <div class="wrapper-content1">
        <div class="bg-gray">
        </div>
        <div class="content-item">
            <p class="content-title">
                The Hot Collection <br>
                <span>summer sale</span>
            </p>
            <p class="content-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab animi atque beatae blanditiis eum fuga
                incidunt iusto maxime nam
            </p>
            <p class="content-more">
                <a href="#">shop now →</a>
            </p>
            <p class="content-shadow">summer</p>
        </div>
    </div>
    <div class="wrapper-content2">
        <div class="content-item">
            <p class="content-title">
                Stylish & Trendy <br>
                <span>bags & accessories</span>
            </p>
            <p class="content-text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab animi atque beatae blanditiis eum fuga
                incidunt iusto maxime nam
            </p>
            <p class="content-more">
                <a href="#">shop now →</a>
            </p>
            <p class="content-shadow">fashion</p>
        </div>
        <div class="bg-gray">
        </div>
    </div>
</div>
