<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 */
?>

<div class="featured">
    <div class="featured-categories featured-shoes">
        <p class="featured-title">
            <a href="#">summer shoes →</a>
        </p>
        </p>
    </div>
    <div class="featured-categories featured-trends">
        <p class="featured-title">
            <a href="#">new trends →</a>
        </p>
    </div>
</div>