<?php

declare(strict_types=1);

/** @var Template block */

use Magento\Framework\View\Element\Template;

?>

<div class="features">
    <div class="features-item features-delivery">
        <h5 class="features-title">
            free delivery worldwide
        </h5>
        <p class="features-text">
            On all orders over $500
        </p>
    </div>
    <div class="features-item features-return">
        <h5 class="features-title">
            flexible return policy
        </h5>
        <p class="features-text">
            If ordered items damaged
        </p>
    </div>
    <div class="features-item features-payment">
        <h5 class="features-title">
            secure payment gateway
        </h5>
        <p class="features-text">
            100% secured merchant
        </p>
    </div>
</div>