<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<div class="slider">
    <div data-mage-init='{"slickTheme1":{"slickOptions":{"slidesToShow":1, "arrows": false, "dots": true, "dotsClass": "slider-dots", "responsive": [{"breakpoint":1024,"settings":{"dots": true, "arrows": false}}, {"breakpoint":600,"settings":{"dots": false, "arrows": false}}, {"breakpoint":480,"settings":{"dots": false, "arrows": false}}]}}}'>
    <div class="slider-item">
        <div class="title"><?= $block->escapeHtml(__('Collection')) ?>
            <span><?= $block->escapeHtml(__('2018')) ?></span>
        </div>
        <strong class="subtitle"><?= $escaper->escapeHtml(__('New Arrivals')) ?></strong>
        <p class="intro"><a class="arrow" href="#">Discover more items →</a></p>
        <span class="title-slider-counter animate__animated animate__fadeOut animate__slower animate__infinite"><?= $escaper->escapeHtml(__('1 of 3')) ?></span>
    </div>
    <div class="slider-item">
        <span class="slider-counter animate__animated animate__fadeOut animate__slower animate__delay-1s animate__infinite"><?= $escaper->escapeHtml(__('2 of 3')) ?></span>
    </div>
    <div class="slider-item">
        <span class="slider-counter animate__animated animate__fadeOut animate__slower animate__infinite"><?= $escaper->escapeHtml(__('3 of 3')) ?></span>
    </div>
</div>
</div>

